### ISSUE TITLE
Bug in ProcessHandler

### ISSUE THREAD

**Issue by pfg666** [protocol-fuzzing/protocol-state-fuzzer#21]
The [ProcessHandler](https://github.com/protocol-fuzzing/protocol-state-fuzzer/blob/fc921da36b87e05fdf76961f9a5c7d603b253820/src/main/java/com/github/protocolfuzzing/protocolstatefuzzer/components/sul/core/sulwrappers/ProcessHandler.java#L16)  class is built on a version of the class in DTLS-Fuzzer which contained an insidious bug.  The issue was that, unless the `-ros` option was used, the handler was not reading from the two InputStreams of the Process instance (connected to output/error streams of the actual process). As a result, buffers in these InputStreams  were getting loaded more and more. For verbose SUTs they would reach full capacity, causing a hang upon a read. 

We fixed the issue, however, ProtocolState-Fuzzer builds on the version of ProcessHandler before the fix. It should switch to the fixed variant, which is [here](https://github.com/assist-project/dtls-fuzzer/blob/1f8dba7085681d11906e875dc7b98f2ba6a5026b/src/main/java/se/uu/it/dtlsfuzzer/sut/ProcessHandler.java#L20).

**Comment by actyp** [comment]
I will fix it, but I want to note the following:

* I will use `OutputStream.nullOutputStream()` from `java.io` instead of `NullOutputStream.getInstance()` from `log4j` used [here](https://github.com/assist-project/dtls-fuzzer/blob/1f8dba7085681d11906e875dc7b98f2ba6a5026b/src/main/java/se/uu/it/dtlsfuzzer/sut/ProcessHandler.java#L41).

* Should [this](https://github.com/assist-project/dtls-fuzzer/blob/1f8dba7085681d11906e875dc7b98f2ba6a5026b/src/main/java/se/uu/it/dtlsfuzzer/sut/ProcessHandler.java#L88) be `currentProcess.getInputStream()` as it is or `currentProcess.getOutputStream()` ?

**Comment by pfg666** [comment]
It is much better to use the package from `java.io`. I believe it should be `currentProcess.getInputStream()`, which returns the input stream connected to the process's output stream. The fix pipes this input stream, along with the error input stream, either to a null or to streams provided via the `redirectOutput` and `redirectError` methods.
