### ISSUE TITLE
where is the sendMessage Method implemented?

### ISSUE THREAD

**Issue by 5angjun** [protocol-fuzzing/protocol-state-fuzzer#68]
Hello, I'm sangjun who is really interested in your project.

While i reviewing your protocol-state-fuzzer with dtls-fuzzer, i wonder what `sendMessage` function is.

the annotation says that `sendMessage` function send the concrete value to SUL like openssl.
but i can't find the concrete body of sendMessage. so i really wonder how does it implemented.

![image](https://github.com/protocol-fuzzing/protocol-state-fuzzer/assets/76202024/11d22090-5a4f-4e1d-b0da-53ae9d3dcb20)

I've been searching for several days for the implementation of the sendMessage method within our project, but I've been unable to locate where it is implemented. This method is declared as abstract in the InputMapper class, and I am supposed to find its concrete implementation in a subclass.

Could anyone point me to the correct file or module where sendMessage is implemented? This information is crucial for my current tasks related to protocol message handling.

Thank you!

**Comment by actyp** [comment]
### DTLS-Fuzzer commit for ProtocolState-Fuzzer

**DTLS-Fuzzer** uses a specific commit of the **ProtocolState-Fuzzer** repo, currently `68e0eea`, which points to this [version of the protocol-state-fuzzer](https://github.com/protocol-fuzzing/protocol-state-fuzzer/tree/68e0eeae05bb6018a1538326df26e47c2e31faf8). So I suggest you browse that version of **ProtocolState-Fuzzer** for the **DTLS-Fuzzer** case.

I will use the `master` branch of **DTLS-Fuzzer** and the `68e0eea` commit of **ProtocolState-Fuzzer** for the following explanation.

### MapperComposer: InputMapper and OutputMapper

**ProtocolState-Fuzzer** provides the [MapperComposer](https://github.com/protocol-fuzzing/protocol-state-fuzzer/blob/68e0eeae05bb6018a1538326df26e47c2e31faf8/src/main/java/com/github/protocolfuzzing/protocolstatefuzzer/components/sul/mapper/mappers/MapperComposer.java) class that implements the [Mapper](https://github.com/protocol-fuzzing/protocol-state-fuzzer/blob/68e0eeae05bb6018a1538326df26e47c2e31faf8/src/main/java/com/github/protocolfuzzing/protocolstatefuzzer/components/sul/mapper/Mapper.java) interface.

The **MapperComposer** needs an InputMapper and an OutputMapper as constructor arguments.

### DTLS-Fuzzer: PhasedMapper and ExecuteInputHelper

**DTLS-Fuzzer** uses the [PhasedMapper](https://github.com/assist-project/dtls-fuzzer/blob/master/src/main/java/se/uu/it/dtlsfuzzer/components/sul/mapper/PhasedMapper.java) class to extend the MapperComposer, but if you check its constructor, it does not provide an InputMapper and uses an [ExecuteInputHelper](https://github.com/assist-project/dtls-fuzzer/blob/master/src/main/java/se/uu/it/dtlsfuzzer/components/sul/mapper/ExecuteInputHelper.java) instead.

The **ExecuteInputHelper** class is responsible for sending messages/records. Specifically, it uses the `sendRecords` method, which uses a **SendMessageHelper** class that comes from **tlsattacker**.

So that is why you couldn't find the implementation of `InputMapper#sendMessage`, because in the case of **DTLS-Fuzzer** the **InputMapper** class is not used.

**Comment by 5angjun** [comment]
Oh i got it. really thanks for your answer.
😀😀
